# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        env:
          # Werror is not enabled on humble and iron because of gtest
          - ROS_DISTRO: rolling
            ROS_REPO: testing
            CMAKE_ARGS: -DCMAKE_CXX_FLAGS=-Werror
          - ROS_DISTRO: rolling
            ROS_REPO: main
            CMAKE_ARGS: -DCMAKE_CXX_FLAGS=-Werror
          - ROS_DISTRO: iron
            ROS_REPO: testing
          - ROS_DISTRO: iron
            ROS_REPO: main
          - ROS_DISTRO: humble
            ROS_REPO: testing
          - ROS_DISTRO: humble
            ROS_REPO: main

    env:
      BASEDIR: ${{ github.workspace }}/.work
      UPSTREAM_WORKSPACE: upstream.repos

    name: ${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: ici
        name: Run industrial_ci
        uses: ros-industrial/industrial_ci@master
        env: ${{ matrix.env }}
      - name: Upload test artifacts (on failure)
        uses: actions/upload-artifact@v2
        if: failure() && (steps.ici.outputs.run_target_test || steps.ici.outputs.target_test_results)
        with:
          name: test-results-${{ matrix.env.NAME }}
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
      - name: Upload log artifacts (on failure)
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results-${{ matrix.env.NAME }}
          path: ${{ env.BASEDIR }}/target_ws/log/*
